---

name: Cron actions

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-labels:
    name: Update labels
    uses: RegioHelden/github-reusable-workflows/.github/workflows/sync-labels.yaml@main
