---

name: Build

on:
  - push
  - pull_request

jobs:
  lint:
    uses: RegioHelden/github-reusable-workflows/.github/workflows/python-ruff.yaml
    with:
      ruff-version: "0.9.9"
      python-version: "3.12"
